### ISSUE TITLE
Architectural block diagram design

### ISSUE THREAD

**Issue by mattheworris** [AmplicaLabs/account-service#2]
## Goal
The goal of this issue is to create an architectural diagram for the account-service

## Discussion
This diagram will serve as a starting point and reference design.

## Acceptance Criteria
 - [x] All necessary modules are fully documented and the diagram is added to the `account-service` repo.
 - [x] This diagram should be updated to reflect changes during development.

**Comment by mattheworris** [comment]
Here is the diagram for reference:

[Gateway Account Service v0.1.0](https://drive.google.com/file/d/11BxZhLMs3Y_Lx3dGokD-Rf3NYg5J6_DR/view?usp=drive_link)

**Comment by mattheworris** [comment]
- [ ] Profiles are blocked until DSNP decides where profiles will live.
- [ ] Persistent Storage needs to be addressed in diagram.

**Comment by wilwade** [comment]
Completed.
