### ISSUE TITLE
Port Reconnection service change for redis disconnection

### ISSUE THREAD

**Issue by mattheworris** [AmplicaLabs/account-service#53]
# Goal
In order to properly support container orchestration systems like kubernetes, a service should exit if it cannot fully execute its functions. 
If a `redis` connection is not available the `account-service` should exit.

# Discussion
`account-service` uses an architecture similar to the `reconnection-service` and therefore can directly port the work done to support redis disconnection from this PR: AmplicaLabs/reconnection-service#114

# Acceptance Criteria
- [x] `redis` connection error causes app to exit

**Comment by claireolmstead** [comment]
Success cases:
- when redis is running, then is stopped or an error is thrown

Failure cases:
- when redis is not initially running
